services:
  konsol:
    build:
      context: ./konsol
      dockerfile: Dockerfile
    volumes:
      - db_data:/app/data
      - slides:/app/slide_images
    environment:
      - GOOGLE_ID_TOKEN=
      - GOOGLE_CALENDAR_API_KEY=
      # - COOKIE_SECRET_KEY=
      - COOKIE_SECURE=false
      - DATABASE_URL=sqlite:///app/data/konsol.db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./outer-nginx.conf:/etc/nginx/conf.d/app.conf:ro
    ports:
      - "80:80"
    depends_on:
      - konsol
    restart: unless-stopped

volumes:
  db_data:
  slides:
