// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `settings` table.
    ///
    /// (Automatically generated by Diesel.)
    settings (id) {
        /// The `id` column of the `settings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `dark_mode` column of the `settings` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        dark_mode -> Bool,
        /// The `slide_interval` column of the `settings` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        slide_interval -> Integer,
    }
}
