name: Rust

on:
  push:
    branches: [ "main" ]
    paths: [ "konsol/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "konsol/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (server)
      working-directory: ./konsol
      run: cargo build --verbose --no-default-features --features ssr
    - name: Run tests
      working-directory: ./konsol
      run: cargo test --verbose --features ssr
